### PR TITLE
fix: ensure docSchemas only contains non-dereferenced schemas

### LINKED ISSUE #109: `docSchemas.observation` export is unexpectedly dereferenced
Potentially a misunderstanding on my part, but my understanding of the difference between `docSchemas` and `deferencedDocSchemas` is that the latter will fully resolve any definitions (i.e. inline them into the relevant properties) and then remove said definitions from the schema.

At the moment, it seems that the `observation` schema in `docSchemas` is dereferenced when it shouldn't be. More specifically just the `position` definition. For example, the `observations` schema has the following references:

https://github.com/digidem/mapeo-schema/blob/f040cef8b58ceb884d1764d96f22c32d6a3af28c/schema/observation/v5.json#L157-L162

but the resulting output of `docSchemas.observation` removes `"$ref": "#/definitions/position"` and inlines it to the relevant properties (removed irrelevant properties for brevity):

```json
    "observation": {
        "definitions": {
            "position": {
                "description": "Position details",
                "type": "object",
                "required": [
                    "mocked"
                ],
                "properties": {
                    "timestamp": {
                        "description": "Timestamp of when the current position was obtained",
                        "type": "string",
                        "format": "date-time"
                    },
                    "mocked": {
                        "description": "`true` if the position was mocked",
                        "type": "boolean",
                        "default": false
                    },
                    "coords": {
                        "description": "Position details, should be self explanatory. Units in meters",
                        "type": "object",
                        "properties": {
                            "latitude": {
                                "type": "number"
                            },
                            "longitude": {
                                "type": "number"
                            },
                            "altitude": {
                                "type": "number"
                            },
                            "heading": {
                                "type": "number"
                            },
                            "speed": {
                                "type": "number"
                            },
                            "accuracy": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "properties": {
            "metadata": {
                "description": "Additional metadata associated with the observation (e.g. location precision, altitude, heading)",
                "type": "object",
                "properties": {
                    "position": {
                        "description": "Position details",
                        "type": "object",
                        "required": [
                            "mocked"
                        ],
                        "properties": {
                            "timestamp": {
                                "description": "Timestamp of when the current position was obtained",
                                "type": "string",
                                "format": "date-time"
                            },
                            "mocked": {
                                "description": "`true` if the position was mocked",
                                "type": "boolean",
                                "default": false
                            },
                            "coords": {
                                "description": "Position details, should be self explanatory. Units in meters",
                                "type": "object",
                                "properties": {
                                    "latitude": {
                                        "type": "number"
                                    },
                                    "longitude": {
                                        "type": "number"
                                    },
                                    "altitude": {
                                        "type": "number"
                                    },
                                    "heading": {
                                        "type": "number"
                                    },
                                    "speed": {
                                        "type": "number"
                                    },
                                    "accuracy": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    },
                    "lastSavedPosition": {
                        "description": "Position details",
                        "type": "object",
                        "required": [
                            "mocked"
                        ],
                        "properties": {
                            "timestamp": {
                                "description": "Timestamp of when the current position was obtained",
                                "type": "string",
                                "format": "date-time"
                            },
                            "mocked": {
                                "description": "`true` if the position was mocked",
                                "type": "boolean",
                                "default": false
                            },
                            "coords": {
                                "description": "Position details, should be self explanatory. Units in meters",
                                "type": "object",
                                "properties": {
                                    "latitude": {
                                        "type": "number"
                                    },
                                    "longitude": {
                                        "type": "number"
                                    },
                                    "altitude": {
                                        "type": "number"
                                    },
                                    "heading": {
                                        "type": "number"
                                    },
                                    "speed": {
                                        "type": "number"
                                    },
                                    "accuracy": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    },
                },
                "additionalProperties": false
            }
        },
    }
```

My expectation is that the `"$ref": "#/definitions/position"` is kept in the outputted schema object. 

<details>
<summary>Here is the whole output of docSchemas.observation</summary>

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://mapeo.world/schemas/observation/v5.json",
  "title": "Observation",
  "description": "An observation is something that has been observed at a particular time and place. It is a subjective statement of 'I saw/heard this, here'",
  "definitions": {
    "position": {
      "description": "Position details",
      "type": "object",
      "required": [
        "mocked"
      ],
      "properties": {
        "timestamp": {
          "description": "Timestamp of when the current position was obtained",
          "type": "string",
          "format": "date-time"
        },
        "mocked": {
          "description": "`true` if the position was mocked",
          "type": "boolean",
          "default": false
        },
        "coords": {
          "description": "Position details, should be self explanatory. Units in meters",
          "type": "object",
          "properties": {
            "latitude": {
              "type": "number"
            },
            "longitude": {
              "type": "number"
            },
            "altitude": {
              "type": "number"
            },
            "heading": {
              "type": "number"
            },
            "speed": {
              "type": "number"
            },
            "accuracy": {
              "type": "number"
            }
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "schemaName": {
      "description": "Must be `observation`",
      "type": "string",
      "const": "observation"
    },
    "lat": {
      "description": "latitude of the observation",
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "lon": {
      "description": "longitude of the observation",
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "refs": {
      "type": "array",
      "description": "References to any nodes or ways that this observation is related to.",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "hex-encoded id of the element that this observation references",
            "type": "string"
          }
        },
        "required": [
          "id"
        ]
      }
    },
    "attachments": {
      "type": "array",
      "description": "media or other data that are attached to this observation",
      "items": {
        "type": "object",
        "properties": {
          "driveId": {
            "type": "string",
            "description": ""
          },
          "name": {
            "type": "string",
            "description": "name of the attachment"
          },
          "type": {
            "type": "string",
            "description": "string that describes the type of the attachment",
            "meta:enum": {
              "UNRECOGNIZED": "future attachment type"
            },
            "enum": [
              "photo",
              "video",
              "audio",
              "UNRECOGNIZED"
            ]
          }
        },
        "required": [
          "driveId",
          "name",
          "type"
        ]
      }
    },
    "tags": {
      "type": "object",
      "description": "User-defined key-value pairs relevant to this observation",
      "properties": {},
      "additionalProperties": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "number"
          },
          {
            "type": "string"
          },
          {
            "type": "null"
          },
          {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "number"
                },
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        ]
      }
    },
    "metadata": {
      "description": "Additional metadata associated with the observation (e.g. location precision, altitude, heading)",
      "type": "object",
      "properties": {
        "manualLocation": {
          "description": "Whether location has been set manually",
          "type": "boolean",
          "default": false
        },
        "position": {
          "description": "Position details",
          "type": "object",
          "required": [
            "mocked"
          ],
          "properties": {
            "timestamp": {
              "description": "Timestamp of when the current position was obtained",
              "type": "string",
              "format": "date-time"
            },
            "mocked": {
              "description": "`true` if the position was mocked",
              "type": "boolean",
              "default": false
            },
            "coords": {
              "description": "Position details, should be self explanatory. Units in meters",
              "type": "object",
              "properties": {
                "latitude": {
                  "type": "number"
                },
                "longitude": {
                  "type": "number"
                },
                "altitude": {
                  "type": "number"
                },
                "heading": {
                  "type": "number"
                },
                "speed": {
                  "type": "number"
                },
                "accuracy": {
                  "type": "number"
                }
              }
            }
          }
        },
        "lastSavedPosition": {
          "description": "Position details",
          "type": "object",
          "required": [
            "mocked"
          ],
          "properties": {
            "timestamp": {
              "description": "Timestamp of when the current position was obtained",
              "type": "string",
              "format": "date-time"
            },
            "mocked": {
              "description": "`true` if the position was mocked",
              "type": "boolean",
              "default": false
            },
            "coords": {
              "description": "Position details, should be self explanatory. Units in meters",
              "type": "object",
              "properties": {
                "latitude": {
                  "type": "number"
                },
                "longitude": {
                  "type": "number"
                },
                "altitude": {
                  "type": "number"
                },
                "heading": {
                  "type": "number"
                },
                "speed": {
                  "type": "number"
                },
                "accuracy": {
                  "type": "number"
                }
              }
            }
          }
        },
        "positionProvider": {
          "description": "Details of the location providers that were available on the device when the observation was recorded",
          "type": "object",
          "properties": {
            "gpsAvailable": {
              "description": "Whether the user has enabled GPS for device location (this is not the same as whether location is turned on or off, this is a device setting whether to use just wifi and bluetooth or use GPS for location)",
              "type": "boolean"
            },
            "passiveAvailable": {
              "description": "Whether the device is configured to lookup location based on wifi and bluetooth networks",
              "type": "boolean"
            },
            "locationServicesEnabled": {
              "description": "Has the user enabled location services on the device (this is often turned off when the device is in airplane mode)",
              "type": "boolean"
            },
            "networkAvailable": {
              "description": "Whether the device can lookup location based on cell phone towers",
              "type": "boolean"
            }
          }
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "schemaName",
    "tags",
    "refs",
    "attachments",
    "metadata"
  ],
  "additionalProperties": false
}
```
</details>

### PR DESCRIPTION
**Pull request by achou11**
Fixes #109

### CODE REVIEW

File: scripts/lib/generate-jsonschema-exports.js [hunk 1]
```diff
@@ -25,7 +25,11 @@ export async function generateJSONSchemaExports(jsonSchemas) {
 
   for (const [schemaName, jsonSchema] of Object.entries(jsonSchemas.merged)) {
     docSchemas[schemaName] = jsonSchema
-    const dereferencer = new JsonSchemaDereferencer(jsonSchema)
+    const dereferencer = new JsonSchemaDereferencer(
+      // Need to create a deep clone to avoid issue described in https://github.com/digidem/mapeo-schema/issues/109
+      JSON.parse(JSON.stringify(jsonSchema)),
+      { mutate: false }
```
Comment (achou11) [inline scripts/lib/generate-jsonschema-exports.js:31]: Specifying this option to future-proof and make it clearer for us, even though the implementation from `@json-schema-tools/dereferencer` is broken

**Review by gmaclennan — APPROVED** [review]
